import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Particle from './components/Particle';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta charSet='UTF-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <meta
          name='description'
          content='This website belongs to shishir adhikari'
        />
        <meta
          name='keywords'
          content='Shishir ,Shishir Adhikari, React, React Developer , Svelte Developer , Front end Developer , Web Developer '
        />
        <title>Shishir Adhikari</title>
        {/*main css file should not be removed */}
        <link rel='stylesheet' href='/css/index.css' />
        <script src='https://cdnjs.cloudflare.com/ajax/libs/gsap/3.2.6/gsap.min.js'></script>
        {/*main css file*/}
        {/*favicon-img*/}
        <link rel='icon' type='image/png' href='/images/favicon.png' />
        {/*favicon-img*/}
      </head>
      <body className={inter.className}>
        <div id='all'>
          {/*mouse  follower*/}
          <div className='cursor' />
          {/*mouse  follower*/}
          {/*loader*/}
          <div id='loader'>
            <span className='color'>Shishir</span>Adhikari
          </div>
          {/*loader-end*/}
          {/*link-screen*/}
          <div id='breaker'></div>
          <div id='breaker-two'></div>

          {/*link-screen*/}
          {/*Main-Section*/}
          {/*Navigator-fullscreen*/}
          <div id='navigation-content'>
            <div className='logo'>
              <img src='images/logo.png' alt='logo' />
            </div>
            <div className='navigation-close'>
              <span className='close-first' />
              <span className='close-second' />
            </div>
            <div className='navigation-links'>
              <a href='/' data-text='HOME' id='home-link'>
                HOME
              </a>
              <Link href='/about' data-text='ABOUT' id='about-link'>
                ABOUT
              </Link>
              <a href='/blog' data-text='BLOG' id='blog-link'>
                BLOG
              </a>
              <a href='/portfolio' data-text='PORTFOLIO' id='portfolio-link'>
                PORTFOLIO
              </a>
              <a href='/contact' data-text='CONTACT' id='contact-link'>
                CONTACT
              </a>
            </div>
          </div>
          {/*Navigator-Fullscreen END*/}

          {/*Menubar*/}
          <div id='navigation-bar'>
            <img src='images/logo.png' alt='logo' />
            <div className='menubar'>
              <span className='first-span' />
              <span className='second-span' />
              <span className='third-span' />
            </div>
          </div>
          {/*Menubar End*/}
          <main>{children}</main>
          {
            <>
              <script src='/js/jquery.min.js'></script>
              <script src='/js/index.js'></script>
            </>
          }
        </div>
      </body>
    </html>
  );
}
